# Generated by Django 5.0.3 on 2024-03-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
